### PR TITLE
Observability in microservice based architecture

### PR DESCRIPTION
**Pull request by guerrerotook**
This PR is for the issue #444. I had to create a new PR because the master branch was renamed to main and I had conflicts. The old PR with all the changes approved is this one, #546. Hope this PR is quicker.

### CODE REVIEW

**Review by TessFerrandez — APPROVED** [review]
Please merge in main - there are some changes (e.g. the readme.md is no README.md) and the link that this is failing on is taken care of.

**Comment by guerrerotook** [comment]
Thanks @TessFerrandez, I still need one more approval.

**Review by NarmathaBala — APPROVED** [review]
Thanks for your contributions @Luis and for working through all the suggestions

**Comment by guerrerotook** [comment]
Thanks @NarmathaBala why I can't accept the merge, can you?

**Pull request merged**
