### PR TITLE
remove internal guidance from public contributing.md page

### PR DESCRIPTION
**Pull request by TechnicallyWilliams**
# Pull Request Template

## What are you trying to address

- A reference to a cse internal wiki page. Removing this reference will make the experience for all readers more uniform.
- #624 

## Description of new changes

- Remove sentence from [#how-to-contribute](https://github.com/microsoft/code-with-engineering-playbook/blob/f36c246aa48750131f75ca1ed6de24cb07f516db/CONTRIBUTING.md#how-to-contribute) section which guides contributors to an internal page.

## For all pull requests

- [x] Link to the issue you are solving (so it gets closed)
- [ ] Label the pull request with the appropriate area(s)
- [ ] Assign potential reviewers (you may also want to contact them on Teams to ensure timely reviews)
- [ ] Assign the project - Engineering Playbook Backlog
- [ ] Assign the pull request to yourself

### CODE REVIEW

**Comment by TechnicallyWilliams** [comment]
Currently, I'm not able to identify which link the markdown-link-check thinks is broken. Will revisit shortly.

**Comment by TechnicallyWilliams** [comment]
PR #645 should address the broke links discovered by the markdown-link-check.

**Comment by TechnicallyWilliams** [comment]
As this is a docs issue, i'm adding @magencio.

**Review by magencio — APPROVED** [review]

**Review by TessFerrandez — APPROVED** [review]
LGTM!

**Pull request merged**
