### PR TITLE
Add KIND DevContainer to help with debugging CRDs

### PR DESCRIPTION
**Pull request by JasonTheDeveloper**
This PR introduces a quick guide including samples showing how you can quickly run and debug CRDs written using kubebuilder locally using dev containers.

### CODE REVIEW

**Comment by TessFerrandez** [comment]
This is a big sample with lots of code - does this really fit in the code-with-engineering-playbook - perhaps it fits better in an internal code share?
cc @fnocera

**Comment by fnocera** [comment]
Hi @JasonTheDeveloper thanks for this contribution. As @TessFerrandez mentioned this is a large code contribution so would be good to sync up to determine whether this should live in the playbook or in a CSEShare code repository. Would you mind reaching out to me and setting up some time to discuss? Thanks!

**Comment by charleszipp** [comment]
I would suggest reusable dev container assets be submitted to the vscode dev container repo. This repo has a directory [here](https://github.com/microsoft/vscode-dev-containers/tree/master/containers) specifically for these types of reusable dev container templates. Its also likely more discoverable from this repo rather than the playbook. cc @fnocera

**Comment by TessFerrandez** [comment]
This has now been open for a while, with the suggestion to move the code to a different repo - should we abandon this PR at this point? or is there still text content from this that is applicable to the code book?

**Comment by fnocera** [comment]
@JasonTheDeveloper please open this PR on https://github.com/microsoft/vscode-dev-containers/tree/master/containers.

**Pull request closed without merging**
