### PR TITLE
Update to reflect addition of team manifesto - ignore

### PR DESCRIPTION
**Pull request by bsherwin**
With the addition of the Team Manifesto, this update links to that document. Where the working agreement covers all aspects of the team engagement, the Team Manifesto is designed to reflect the technical agreement among the developers for how code is delivered to the project.

Incorporated changes from https://github.com/microsoft/code-with-engineering-playbook/pull/509 that was abandoned because of missing repository.

### CODE REVIEW

**Review by gldnblgty — APPROVED** [review]

**Review by TessFerrandez — APPROVED** [review]

**Comment by TessFerrandez** [comment]
@bsherwin I see this is failing on an unrelated link - I have asked @katyamust to add an exception in her PR - once that is done we can merge in main for this to get that exception - or alternatively add it to the exception list here too and then we'll figure out the merge later

**Comment by gldnblgty** [comment]
@bsherwin seems that the problem link is removed from the observability doc in master branch.. 
not a clean thing for PR but since situation is exceptional, just removing the link in this PR should solve the problem. it's already not in master. CC: @katyamust , @tessFernandez

**Comment by fnocera** [comment]
Once #607 is merged in all outstanding PRs including this one will have to make a few changes and merge master to adopt the new MKDocs structure. This main change is that all the md files move into a `docs` folder. Please don't hesitate to reach out with any questions and a number of us are more than happy to help with this process - reach out to @fnocera @TessFerrandez @omri374 and @brockneedscoffee

**Comment by bsherwin** [comment]
This PR will be closed because changes were made in base repository that were reflected in #617 which is now the official PR for this change.

**Comment by bsherwin** [comment]
This content was merged in PR #617

**Pull request closed without merging**
