### PR TITLE
Add golangci-lint to Go Code reviews 

### PR DESCRIPTION
**Pull request by lawrencegripper**
`golangci-lint` is an alternative to `gometalinter` which performance improvements and additional features that make it easy to introduce into an existing code-base.

### CODE REVIEW

**Comment by lawrencegripper** [comment]
Further note on this one as `Gometalinter` has now been marked depreciated by the project owner. Given this are we happy for me to update the PR to remove it from the guidance https://github.com/alecthomas/gometalinter/issues/590

**Comment by lawrencegripper** [comment]
@DanMass are you happy for me to update to `golangci-lint` now `gometalinter` has been depreciated?

**Comment by lawrencegripper** [comment]
Quick nudge on this one: Who is the reviewer for golang stuff?

**Comment by Nepomuceno** [comment]
I do approve this changes 😉 
@lawrencegripper

**Comment by fnocera** [comment]
@lawrencegripper the playbook has undergone a facelift/structural change, could you please rebase and update the PR?

**Comment by lawrencegripper** [comment]
@fnocera done :)

**Comment by lawrencegripper** [comment]
I've fixed up some more as `gometalinter` is no more so have removed.

**Pull request merged**
