### PR TITLE
Sustainability addition to the playbook

### PR DESCRIPTION
**Pull request by hybridflux**
# Pull Request Template

## What are you trying to address

The choices made throughout the engineering process regarding cloud services, software architecture
design and automation can have a big impact on the carbon footprint of a solution. This addition to the playbook prompts engineers to think about the carbon emission impact of design choices made throughout the software design and development process. 

## Description of new changes

Adds sustainability considerations to engineering process.

## For all pull requests

- [ ] Link to the issue you are solving (so it gets closed)
- [x] Label the pull request with the appropriate area(s)
- [x] Assign potential reviewers (you may also want to contact them on Teams to ensure timely reviews)
- [x] Assign the project - Engineering Playbook Backlog
- [x] Assign the pull request to yourself

### CODE REVIEW

**Comment by hybridflux** [comment]
Currently, the link checker is failing in another part of the playbook (privacy) - it may be solved by the next PR that gets merged:
image

**Review by wbreza — APPROVED** [review]
Looks great! thanks for the contribution!

**Comment by wbreza** [comment]
@hybridflux - Looks like the build is passing now :)

**Comment by fnocera** [comment]
Thank you so much for this content - I would suggest adding this as a section under `design`. We try and keep the number of top level "fundamentals" somewhat limited. 

cc: @wbreza @TessFerrandez @xtophs

**Comment by TessFerrandez** [comment]
> Thank you so much for this content - I would suggest adding this as a section under `design`. We try and keep the number of top level "fundamentals" somewhat limited.
> 
> cc: @wbreza @TessFerrandez @xtophs

That sounds like a nice fit, agree on keeping the number of top level fundamentals limited - for both readability and management

**Review by TessFerrandez — CHANGES_REQUESTED** [review]
Marking as request changes to move the content into the design section rather than as a top-level section

**Comment by hybridflux** [comment]
> > Thank you so much for this content - I would suggest adding this as a section under `design`. We try and keep the number of top level "fundamentals" somewhat limited.
> > cc: @wbreza @TessFerrandez @xtophs
> 
> That sounds like a nice fit, agree on keeping the number of top level fundamentals limited - for both readability and management

@fnocera @TessFerrandez thanks for your comments, moved the doc to design section

cc: @wbreza @xtophs

**Review by magencio — APPROVED** [review]

**Comment by xtophs** [comment]
@TessFerrandez: Did we make the required changes?

**Review by TessFerrandez — APPROVED** [review]
LGTM

**Comment by hybridflux** [comment]
Still pending approval from @fnocera 

cc: @xtophs

**Comment by xtophs** [comment]
markdownlint / lint messages addressed in PR #761

**Pull request merged**
