### PR TITLE
Add kubernetes-at-the-edge packaged sprint as projector workItemTemplate

### PR DESCRIPTION
**Pull request by vyta**
# Pull Request Template

## What are you trying to address

Adding a packaged sprint for the kubernetes at the edge scenario work as a projector workItemTemplate

## Description of new changes

Add new file, kubernetes-at-the-edge.yml, to workItemTemplates

## For all pull requests

- [ ] Link to the issue you are solving (so it gets closed)
- [ ] Label the pull request with the appropriate area(s)
- [ ] Assign potential reviewers (you may also want to contact them on Teams to ensure timely reviews)
- [ ] Assign the project - Engineering Playbook Backlog
- [ ] Assign the pull request to yourself

### CODE REVIEW

**Comment by vyta** [comment]
I'm unable to add assignees or labels for some reason.. Tagging @tbarlow12 and @zmmille2 as per @microsoft/cseefr guidance.

CC: @fnocera @brockneedscoffee

**Comment by TessFerrandez** [comment]
@vyta Did yo mean to add this to the playbook? - What is this in relation to? and how is this linked from documentation?

**Comment by tbarlow12** [comment]
@TessFerrandez this is in relation to [Projector](https://www.npmjs.com/package/pjr), which was demoed to the Engineering Fundamentals Champions Leads a few weeks ago and approved for use by that group.

We do already have a [template for engineering fundamentals](https://github.com/microsoft/code-with-engineering-playbook/blob/main/.projector/workItemTemplates/engineering-fundamentals.yml) in the playbook and the current plan is to have the playbook be the source of truth for these templates going forward.

Feel free to reach out to either myself or @zmmille2 if you have questions

**Comment by fnocera** [comment]
@vyta I added you as a contributor so you should now be able to add labels etc. 

@tbarlow12 I love the idea behind projector and think it is super helpful as long as the content is generally applicable across engagements (eg: the engineering fundamentals template). If we are thinking of adding a lot of these templates we should discuss how these will be maintained going forward. 

cc: @TessFerrandez @wbreza @charleszipp

**Review by wbreza — COMMENTED** [review]
Thanks for the contributions.  We are super glad to see projector making its way into the playbook.  The EF team is still defining exactly how Projector CLI will be incorporated back into the playbook.  Give us a little more time to discuss internally and we'll get back to you on next steps.

**Comment by wbreza** [comment]
> @TessFerrandez this is in relation to [Projector](https://www.npmjs.com/package/pjr), which was demoed to the Engineering Fundamentals Champions Leads a few weeks ago and approved for use by that group.
> 
> We do already have a [template for engineering fundamentals](https://github.com/microsoft/code-with-engineering-playbook/blob/main/.projector/workItemTemplates/engineering-fundamentals.yml) in the playbook and the current plan is to have the playbook be the source of truth for these templates going forward.
> 
> Feel free to reach out to either myself or @zmmille2 if you have questions

tbarlow12 / @z

> @TessFerrandez this is in relation to [Projector](https://www.npmjs.com/package/pjr), which was demoed to the Engineering Fundamentals Champions Leads a few weeks ago and approved for use by that group.
> 
> We do already have a [template for engineering fundamentals](https://github.com/microsoft/code-with-engineering-playbook/blob/main/.projector/workItemTemplates/engineering-fundamentals.yml) in the playbook and the current plan is to have the playbook be the source of truth for these templates going forward.
> 
> Feel free to reach out to either myself or @zmmille2 if you have questions

@tbarlow12 / @zmmille2 - It would be great for you to help define a folder structure and plan for how Projector templates could be integrated back into the playbook.  If we followed the pattern of the current PR I would be afraid of it turning into a large laundry list of templates vs a more organized structure by EF area.

**Review by zmmille2 — APPROVED** [review]
Thank you for this. @wbreza, projector needs a quick change to make sure we can accommodate a nested structure - I want to merge this in while we get that into projector, and then I can suggest a nested structure and move this and any other work items that come in. I don't want to block this any longer, though.

**Review by wbreza — APPROVED** [review]

**Pull request merged**
