### PR TITLE
Add Terraform Language Server Protocol to Terraform DevContainer

### PR DESCRIPTION
**Pull request by JasonTheDeveloper**
This PR introduces terraform LSP to the Terraform dev container sample. When the dev container builds and launches, LSP will install as well automatically.

### CODE REVIEW

**Comment by TessFerrandez** [comment]
Please link to the issue that this PR is resolving

**Comment by charleszipp** [comment]
I would suggest reusable dev container assets be submitted to the vscode dev container repo. This repo has a directory [here](https://github.com/microsoft/vscode-dev-containers/tree/master/containers) specifically for these types of reusable dev container templates. Its also likely more discoverable from this repo rather than the playbook. cc @fnocera

**Comment by TessFerrandez** [comment]
Per the comments, I have added Issue #360 to remove the containers from this repo.

Should we abandon this PR at this point, and if so, could you @JasonTheDeveloper work with @erikschlegel to move the container to the appropriate repo and make sure that the work you have put down on this PR is captured there as well?

cc: @charleszipp @fnocera

**Comment by fnocera** [comment]
@JasonTheDeveloper please open this PR on https://github.com/microsoft/vscode-dev-containers/tree/master/containers.

**Pull request closed without merging**
