### PR TITLE
Remove Terraform links from CI IaC bullets

### PR DESCRIPTION
**Pull request by jskulavik**

### CODE REVIEW

**Comment by TessFerrandez** [comment]
Why are we removing these links? is there an open issue or can you provide some context?

**Comment by jskulavik** [comment]
We need to remove all references to and notions of the third-party Terraform tool given that it does not align with the goals of this playbook, our code-with practice, or our engineering fundamentals.

**Review by erikschlegel — COMMENTED** [review]
The intent for the original section for IAC is that developers have options beyond ARM. If a customer is already committed to using terraform then we should meeting them where they are.

**Comment by TessFerrandez** [comment]
So then it sounds @erikschlegel that we both think that we should leave the content as is.
@jskulavik if so, my suggestion is that we close this PR without merging, but would like to hear back from you

**Review by TessFerrandez — CHANGES_REQUESTED** [review]
Suggesting to cancel this PR based on the comments above

**Comment by fnocera** [comment]
@jskulavik suggest that we have a meeting (as we discussed over IM) and make sure we are aligned with @brockneedscoffee as well who is coordinating the CI/CD content. Will close this PR for now.

**Pull request closed without merging**
