### PR TITLE
Added README for Performance Testing as part of Automated Testing Content

### PR DESCRIPTION
**Pull request by brunoterkaly**
# In this PR

## What are you trying to address

Jafar made some edits to the original PR. I've responded to those comments in this PR.

## Description of new changes

Simple edits in this PR.

### CODE REVIEW

**Comment by brunoterkaly** [comment]
Thank you, Jafar! Here to help as needed.

**Review by TessFerrandez — APPROVED** [review]

**Comment by TessFerrandez** [comment]
This looks like a duplicate of #667 - can you write a more descriptive title and PR description so that people can review more easily and delete either this one or #667? cc: @alkofahi

Thank you

**Review by alkofahi — APPROVED** [review]

**Review by alkofahi — APPROVED** [review]
Plz address the merge conflict so that we can merge this in, thanks!

**Comment by brunoterkaly** [comment]
> This looks like a duplicate of #667 - can you write a more descriptive title and PR description so that people can review more easily and delete either this one or #667? cc: @alkofahi
> 
> Thank you

Yes. Makes sense. Thanks, Tess!

**Comment by alkofahi** [comment]
Reached out to Bruno to update and merge this PR!

**Comment by wbreza** [comment]
@brunoterkaly - Sorry for the delay on your updates.  Please take a moment to resolve your conflicts, then this update should be good to go!

**Pull request merged**
