### PR TITLE
Commit message/PR title standardization guidance

### PR DESCRIPTION
**Pull request by tbarlow12**
Guidance on standardizing commit message (or PR titles that become commits once squash-merged). Helpful for generating changelog and maintaining clean git history. Wasn't entirely sure if it fits into `code-reviews` or `source-code`, so I tagged as both.

### CODE REVIEW

**Comment by davidkpiano** [comment]
Might be useful to mention that while it would be ideal if PR titles and commit messages are standardized, that's not always feasible or easily enforced (especially with time constraints, and, well, humans aren't perfect).

That's why tools like [Changesets from Atlassian](https://github.com/atlassian/changesets) exist, which is an automated way of enforcing changesets easily without needing a standardized way of writing messages.

**Review by TessFerrandez — APPROVED** [review]
Thank you for the contribution!

**Comment by TessFerrandez** [comment]
@tbarlow12 
1. Do you have rights to merge? if not, ping me on teams and I will merge for you -- would have automatically merged but there was an outstanding question from @davidkpiano and just wanted to see if you wanted to address that or leave it as is
2. Is there an open issue related to this? if so, we should link the issue so that it gets closed as part of the PR

**Comment by tbarlow12** [comment]
> @tbarlow12
> 
> 1. Do you have rights to merge? if not, ping me on teams and I will merge for you -- would have automatically merged but there was an outstanding question from @davidkpiano and just wanted to see if you wanted to address that or leave it as is
> 2. Is there an open issue related to this? if so, we should link the issue so that it gets closed as part of the PR

@TessFerrandez I'll address @davidkpiano's comment and then merge. No open issue, just something that came up in an engagement that seemed worth sharing out. Thanks

**Pull request merged**
