### PR TITLE
fixed broken links

### PR DESCRIPTION
**Pull request by sarahdettorre**
# Pull Request Template

## Resolved broken link

- Resolved broken links that were highlighted in lint checks for a couple of active pull requests

## Description of new changes

- Updated broken Managed Recommended Rules link in code-reviews/recipes/csharp.md
- Removed broken Azure Deploy link in resources/templates/README.md
- Fixed terraform broken links in code-reviews/recipes/terraform.md

## For all pull requests

- [ ] Link to the issue you are solving (so it gets closed)
- [x] Label the pull request with the appropriate area(s)
- [x] Assign potential reviewers (you may also want to contact them on Teams to ensure timely reviews)
- [x] Assign the project - Engineering Playbook Backlog
- [x] Assign the pull request to yourself

### CODE REVIEW

**Review by TessFerrandez — APPROVED** [review]
Thank you much for this @sarahdettorre

**Comment by TessFerrandez** [comment]
@sarahdettorre could you kindly also remove the other broken link (even though it is not in the same area) in this same PR? the azuredeploy one in the resources/templates folder -- that would be very helpful

**Comment by sarahdettorre** [comment]
Removed azure deploy broken link

**Comment by sarahdettorre** [comment]
Fixed terraform broken links

**Review by ikivanc — APPROVED** [review]
Looks good to me, thanks @sarahdettorre

**Pull request merged**
