### PR TITLE
Feature/663 Consumer-driven Contract Testing

### PR DESCRIPTION
**Pull request by marcgs**
# Consumer-driven Contract Testing

## What are you trying to address

In this PR we add an entry to the Automated Testing area of the Playbook on Consumer-driven Contract Testing (CDC).

CDC is a software testing methodology used in many projects to test interactions between components in isolation and thus overcome the painful drawbacks of automated E2E tests requiring a fully integrated environment.

Resolves microsoft/code-with-engineering-playbook#663

## Description of new changes

- A new entry in the Automated Testing area has been created

## For all pull requests

- [x] Link to the issue you are solving (so it gets closed)
- [x] Label the pull request with the appropriate area(s)
- [x] Assign potential reviewers (you may also want to contact them on Teams to ensure timely reviews)
- [x] Assign the project - Engineering Playbook Backlog
- [x] Assign the pull request to yourself

### CODE REVIEW

**Review by omusavi — COMMENTED** [review]
Overall looks good to me. I would love an example of a CDC contract in code and how those tests are written, as well as any additional tips and tricks to writing those contract tests, but that can come in a future PR if you think it would be more helpful that way.

You should also add Contract testing to the table in the main [Automated Testing README](https://github.com/microsoft/code-with-engineering-playbook/tree/main/docs/automated-testing/README.md).

I will wait for Jafar to give final sign-off on this but lgtm

**Comment by marcgs** [comment]
> Overall looks good to me. I would love an example of a CDC contract in code and how those tests are written, as well as any additional tips and tricks to writing those contract tests, but that can come in a future PR if you think it would be more helpful that way.
> 
> You should also add Contract testing to the table in the main [Automated Testing README](https://github.com/microsoft/code-with-engineering-playbook/tree/main/docs/automated-testing/README.md).
> 
> I will wait for Jafar to give final sign-off on this but lgtm

Thanks for your comment. I have added CDC to the main automated testing table.

Regarding code examples, we have linked a sample Java application in the "Resources" section, and I have added a link to an external Pact C# workshop. We thought it would be good to keep this document focused on the concepts and link to external references for coding specifics.

**Comment by alkofahi** [comment]
> Overall looks good to me. I would love an example of a CDC contract in code and how those tests are written, as well as any additional tips and tricks to writing those contract tests, but that can come in a future PR if you think it would be more helpful that way.
> 
> You should also add Contract testing to the table in the main [Automated Testing README](https://github.com/microsoft/code-with-engineering-playbook/tree/main/docs/automated-testing/README.md).
> 
> I will wait for Jafar to give final sign-off on this but lgtm

+1 - but at the same time, I would caution against adding extensive code samples. I think some form of abstraction or snippets might suffice.

+1 to doing that in a future PR

**Review by alkofahi — APPROVED** [review]
LGTM - thanks for your contribution

**Comment by marcgs** [comment]
> > Overall looks good to me. I would love an example of a CDC contract in code and how those tests are written, as well as any additional tips and tricks to writing those contract tests, but that can come in a future PR if you think it would be more helpful that way.
> > You should also add Contract testing to the table in the main [Automated Testing README](https://github.com/microsoft/code-with-engineering-playbook/tree/main/docs/automated-testing/README.md).
> > I will wait for Jafar to give final sign-off on this but lgtm
> 
> +1 - but at the same time, I would caution against adding extensive code samples. I think some form of abstraction or snippets might suffice.
> 
> +1 to doing that in a future PR

Thanks for your review Jafar! We can add an "Applying Consumer-driven Contract Testing" section in a future PR with some guidelines and high level examples without going too much into coding specifics. As I mentioned in my reply to Omeed, we have already linked a sample Java application and a Pact C# coding workshop in the "Resources" section as further references for coding CDC Tests.

**Review by omusavi — APPROVED** [review]
Lgtm, thanks for the contribution!

**Pull request merged**
