### PR TITLE
docs: Guidance on documentation creation, maintenance and sharing [WIP]

### PR DESCRIPTION
**Pull request by tbarlow12**
- Started page of helpful links for documentation generation and maintenance
- Started page considering different options for documentation creation, maintenance and sharing. Still WIP as want to discuss other ideas with Design Review Champions Group
- Open to any feedback - meant to start a discussion and gather ideas from the group

### CODE REVIEW

**Comment by TessFerrandez** [comment]
@tbarlow this has been a work in progress for some time - are you looking for some feedback on it or can I help you progress it in any way?

**Comment by TessFerrandez** [comment]
@magencio This PR could perhaps be a part of the new documentation effort you're driving

**Comment by magencio** [comment]
> @magencio This PR could perhaps be a part of the new documentation effort you're driving
> 
> EDIT: sorry - saw now that you had commented above... do we want to abandon this one and create a new PR as part of #533 in the docs area?

My plan is to finish gathering all the info we already have in the Playbook about Documentation, to identify the gaps, and then use other sources of useful information like the contents of this PR to fill those gaps. As soon as I get there I'll let you know, because it may make sense to do a new PR on top of my PR with the new Documentation section.

**Comment by tbarlow12** [comment]
I'll close this and sync up with @magencio offline. Thanks for the ping @TessFerrandez

**Pull request closed without merging**
