### PR TITLE
Added AzDO PR Extension for VS Code

### PR DESCRIPTION
**Pull request by ankitbko**
Added Azure DevOps Pull Requests Extension for VS Code as described in #580

### CODE REVIEW

**Comment by ankitbko** [comment]
@katyamust Please review

**Review by tompaana — APPROVED** [review]
LGTM

**Review by katyamust — APPROVED** [review]
Thank you!

**Comment by ankitbko** [comment]
Thanks for reviewing. The linting check fails due to incorrectly classifying a link as dead in another file. I don't have permission to re-run the check or merge the PR.

**Pull request merged**
