### PR TITLE
Add observability recipe for trace context propagation

### PR DESCRIPTION
**Pull request by MagdaPaj**
## What are you trying to address

Add a recipe for trace context propagation in the ASP.NET Core application.

## Description of new changes

I tried to keep it simple, just a link to the repository (inside the repo there is a README.md). But if you think that's too short or you have other suggestions, please let me know.

## For all pull requests

- [x] Link to the issue you are solving (so it gets closed)
- [x] Label the pull request with the appropriate area(s)
- [x] Assign potential reviewers (you may also want to contact them on Teams to ensure timely reviews)
- [x] Assign the project - Engineering Playbook Backlog
- [x] Assign the pull request to yourself

### CODE REVIEW

**Review by katyamust — COMMENTED** [review]
Thank you for the great content, Magda! 

In the repo your team is created sample code that would extract trace context related header from HTTP request headers. The HTTP request headers are monitored automatically by App Insights, but it does not collect these headers automatically and sample code does.
Did I understood this correctly?

**Review by katyamust — CHANGES_REQUESTED** [review]
As we discussed:

Adding points on what project in doing in reference repo in more concrete terms  to help reader understand what the sample code is trying to achieve that is not supported by App Insights.

**Comment by MagdaPaj** [comment]
@katyamust thanks for your feedback. I improved the introduction in the [readme](https://github.com/MagdaPaj/application-insights-aspnet-sample-trace-context-propagation#distributed-trace-context-propagation-code-sample), could you have a look if now it's more clear?

**Review by NarmathaBala — APPROVED** [review]
Thanks for the content @MagdaPaj

**Review by syedhassaanahmed — APPROVED** [review]

**Review by katyamust — APPROVED** [review]

**Comment by katyamust** [comment]
> @katyamust thanks for your feedback. I improved the introduction in the [readme](https://github.com/MagdaPaj/application-insights-aspnet-sample-trace-context-propagation#distributed-trace-context-propagation-code-sample). I added a diagram and specify a goal of the sample code. Could you have a look if now it's more clear?

It is much more clear now, thank you!

**Comment by MagdaPaj** [comment]
I still have the markdownlint check reporting a dead link, which in fact is not dead. I see other PRs having the same issue. Not sure how to resolve it. Any suggestions?

**Comment by katyamust** [comment]
> I still have the markdownlint check reporting a dead link, which in fact is not dead. I see other PRs having the same issue. Not sure how to resolve it. Any suggestions?

Merge with main branch, if still getting same problem remove this link. I will escalate this issue.

**Pull request merged**
