### PR TITLE
feature/469-pr-template-consolidation

### PR DESCRIPTION
**Pull request by adrian-gonzalez**
# [469](https://github.com/microsoft/code-with-engineering-playbook/issues/469)

## Description

---

Upon reviewing the various PR Templates (found in both the `code review` and `source control` folders, it become apparent that there was a chance for consolidation.

This change introduces a single PR Template, which includes all the content that was found in all the previous templates. While adding content that provides an explanation for each of the sections.

Although the intent of using separate PRs for change type (bug, feature) is well intended, the actual content didn't appear to deviate sufficiently to merit such a distinction for the templates. In order to still capture the possibility for team's to have separate PR Templates per type, this change adds a note in the PR Template `README.md` that outlines this note.

## PR Checklist

---

- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] My code follows the code style of this project.
- [x] I ran the lint checks which produced no new errors nor warnings for my changes. There is one warning but appears to be a false positive.
- [x] I have checked to ensure there aren't other open Pull Requests for the same update/change.

## Does this introduce a breaking change?

---

- [ ] Yes
- [x] No

> If this introduces a breaking change, please describe the impact and migration path for existing applications below.

### CODE REVIEW

**Comment by TessFerrandez** [comment]
@katyamust I know you were working on this with issue #469 - this seems to be a PR on the exact same issue - can you check and see if this PR is in line with what you had planned?

@adrian-gonzalez Thank you for the contribution - since @katyamust was already assigned to an issue to solve this exact thing, and I know she has at least started working on it, I think it is fair to give her the precedence on this - in case she has already worked on it - but we can probably consolidate the work in that case.

**Comment by adrian-gonzalez** [comment]
Absolutely! I didn't see a branch for the issue but may have jumped the gun too soon - please let me know @katyamust your thoughts and I can help collaborate on anything you have in progress.

**Comment by katyamust** [comment]
@adrian-gonzalez thank you so much for your contirubution, it goes inline with  our vision as well. we have also  agreed to move pull request template excellent content to Code Reviews section where it belongs. Let me suggest a change to your branch implementing what we had in mind in addition to your changes.

**Comment by TessFerrandez** [comment]
Send me a message on teams when you have sorted things out and its ready for review @katyamust @adrian-gonzalez

**Comment by TessFerrandez** [comment]
@katyamust @adrian-gonzalez it has been a little while - did you make the changes to this so I should review?

**Review by katyamust — APPROVED** [review]
I like the idea of consolidating of all pull request templates to one.  There is a lot of duplication  in these documents and new one is concise and clear. I therefore approve this pull request.

**Review by TessFerrandez — APPROVED** [review]
@katyamust looks like you need to pull in the latest changes from main - there is a broken link that has later been fixed

**Pull request merged**
