### PR TITLE
Adding python logger class github repo link to observability recipes.

### PR DESCRIPTION
**Pull request by anandchugh**
# Pull Request Template

## What are you trying to address

- This PR adds an observability recipe which contains a git hub repo for a reusable python logger class using Opencensus for Application insights.

## Description of new changes

- This PR adds a link to Azure Samples GitHub repo for python logger class using Opencensus for Application insights.

## For all pull requests

- [Issue ] (https://github.com/microsoft/code-with-engineering-playbook/issues/631)
- [ ] Label the pull request with the appropriate area(s)
- [ ] Assign potential reviewers (you may also want to contact them on Teams to ensure timely reviews)
- [ ] Assign the project - Engineering Playbook Backlog
- [ ] Assign the pull request to yourself

### CODE REVIEW

**Review by katyamust — APPROVED** [review]
Thank you for contribution!

**Review by katyamust — APPROVED** [review]
Anand, could you update the PR description to reflect what is being added.

**Review by TessFerrandez — APPROVED** [review]
Please merge in the current main branch to fix the problem you're getting on the link checker

**Comment by anandchugh** [comment]
Closing this PR as I have created another PR https://github.com/microsoft/code-with-engineering-playbook/pull/634.
This was done was branch was renamed from master to main.

**Pull request closed without merging**
